branch-defaults:
  default:
    environment: flask-env
global:
  application_name: flask-tutorial
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
